#!/bin/bash

set -x

BUILDS_HOME=/tmp/jenkins
BUILDS_URL=http://10.6.154.240:8080
# Change the HOST prefix from ds- if you set it to something different in the Jenkins system config.
HOST=dynaslave-$(hostname)
SLAVE_DIR=${BUILDS_HOME}/slave
SLAVE_TOOLS=${BUILDS_HOME}/tools
SLAVE_JAR=${BUILDS_URL}/jnlpJars/slave.jar
JNLP_URL="${BUILDS_URL}/computer/${HOST}/slave-agent.jnlp"

LOG=${BUILDS_HOME}/jenkins-${HOST}.log

refresh_slave_jar() {
    pushd ${SLAVE_TOOLS}
    curl -O ${SLAVE_JAR}
    popd
}

launch_slave() {
    pkill -f slave.jar
    java -jar ${SLAVE_TOOLS}/slave.jar \
      -jnlpUrl ${JNLP_URL} > ${LOG} &
    JAVA_PID=$!
    echo Slave started as process $$
    echo "java process id forked is: " ${JAVA_PID}
    wait $JAVA_PID
}

main() {
    [[ -d ${BUILDS_HOME}/slave ]] && mkdir -p ${BUILDS_HOME}/slave
    launch_slave
}

main
