#!/bin/bash

set -x

if [ $# -ne 2 ]
then
    echo "Usage: $0 <host> <user>"
    echo "The following was specified:"
    cat /proc/$$/cmdline
    exit 65
fi
slave_node_conn=$2@$1
slave_node=$1
remote_user=$2

runHomeDir="/apps/jenkins"

master_node="10.6.154.240"
keyfile="${runHomeDir}/keys/vagrant-pubkey"

remote_builds_dir=/tmp/jenkins

# TODO this isn't really needed since start-remote-dynaslave does a pkill as well
echo "killing old slave processes"
#ssh -l ${remote_user} -i ${keyfile} ${slave_node} "pgrep -fl slave.jar; pkill -f slave.jar"
ssh -l ${remote_user} -i ${keyfile} ${slave_node_conn} "pgrep -fl slave.jar; pkill -f slave.jar"

if [ ${slave_node} != ${master_node} ]
then
    echo "updating tools"
    ssh -l ${remote_user} -i ${keyfile} ${slave_node_conn} "mkdir -p $remote_builds"
    rsync -au -c -v --delete \
        -e "ssh -l ${remote_user} -i ${keyfile}" \
        ${runHomeDir}/tools ${remote_user}@${slave_node}:${remote_builds_dir}/
fi

echo "launching remote slave process"
ssh -l ${remote_user} -i ${keyfile} ${slave_node_conn} ${remote_builds_dir}/tools/start-dynaslave
